# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

rule all:
    input:
        "outputs/world_map_s2.png",
        "outputs/world_map_from_global_shape.png"

rule world_map_s2:
    input:
        script = "scripts/02_world_map_s2.R"
    output:
        "outputs/world_map_s2.png"
    log:
        "logs/world_map_s2.log"
    conda:
        "envs/environment.yml"
    shell:
        "{input.script} > {log} 2>&1"

rule world_map_from_global_shape:
    input:
        "resources/Large Scale/shp/Admin_0_polygons.shp",
        script = "scripts/03_world_map_from_global_shape.R"
    output:
        "outputs/world_map_from_global_shape.png"
     log:
        "logs/world_map_from_global_shape.log"
    conda:
        "envs/environment.yml"
    shell:
        "{input.script} > {log} 2>&1"
