# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

rule all:
    input:
        "resources/Admin_0_polygons.CPG",
        "resources/Admin_0_polygons.dbf",
        "resources/Admin_0_polygons.prj",
        "resources/Admin_0_polygons.sbn",
        "resources/Admin_0_polygons.sbx",
        "resources/Admin_0_polygons.shp",
        "resources/Admin_0_polygons.shx",
        "results/base_s2.png",
        "results/ggplot_s2.png",
        "results/base_shape.png",
        "results/ggplot_shape.png",
        "results/ggplot_shape_b.png"

rule download_shapefiles:
    input:
        script="workflow/scripts/get_global_map.bash"
    output:
        "resources/Admin_0_polygons.CPG",
        "resources/Admin_0_polygons.dbf",
        "resources/Admin_0_polygons.prj",
        "resources/Admin_0_polygons.sbn",
        "resources/Admin_0_polygons.sbx",
        "resources/Admin_0_polygons.shp",
        "resources/Admin_0_polygons.shx"
    log:
        "logs/download_shapefiles.log"
    conda:
        "envs/environment.yml"
    shell:
        "{input.script} > {log} 2>&1"

rule world_map_s2:
    input:
        script = "workflow/scripts/02_world_map_s2.R"
    output:
        "results/base_s2.png",
        "results/ggplot_s2.png"
    log:
        "logs/world_map_s2.log"
    conda:
        "envs/environment.yml"
    shell:
        "{input.script} > {log} 2>&1"

rule world_map_from_global_shape:
    input:
        "resources/Admin_0_polygons.shp",
        script = "workflow/scripts/03_world_map_from_shape.R"
    output:
        "results/base_shape.png",
        "results/ggplot_shape.png",
        "results/ggplot_shape_b.png"
    log:
        "logs/world_map_from_global_shape.log"
    conda:
        "envs/environment.yml"
    shell:
        "{input.script} > {log} 2>&1"
