name: globe
channels:
  - conda-forge
  - bioconda
  # - r # check if this is compatible
  - nodefaults
dependencies:
  - wget=1.21.4
  - unzip=6.0
  - libarchive=3.7.4
  - snakemake=8.18.1
  - graphviz=12.0.0
  - r-base=4.4.1
  - r-data.table=1.15.4
  - r-languageserver=0.3.16 # this is just to improve the R experience - linting
  - r-terra=1.7_78
  - gdal=3.9.2
  - r-ggplot2=3.5.1
  - r-sf=1.0_16
  - r-ggnewscale=0.5.0
  # - radian=0.6.12 # this is just to improve the R experience - a beautiful console
  # - r-httpgd # this is just to improve the R experience - visualization
  # - r-codetools=0.2_19
  # - r-stringr=1.7.12
  # - r-raster=3.6_20
  # - r-dssat=0.0.7
  # - r-tidyverse=2.0.0
  # - r-soiltexture=1.5.1 # check if this is compatible