name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs: 
      - Linting
      - Formatting
    steps:
    - name: Checkout repostory
      uses: actions/checkout@v2

    - name: Give excecute permission to run get_global_map.bash script
      run: chmod +x workflow/scripts/get_global_map.bash
      
    - name: Give excecute permission to run 02_world_map_s2.R script
      run: chmod +x workflow/scripts/02_world_map_s2.R

    - name: Give excecute permission to run 03_world_map_from_shape.R script
      run: chmod +x workflow/scripts/03_world_map_from_shape.R

    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs --cores 3 --conda-cleanup-pkgs cache --all-temp"

    - name: Test report
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--report report.zip"